#!/usr/bin/env bash
# vim: ft=sh sw=2 et

set -euo pipefail

test() {
  $SNACK build
  $SNACK run | diff golden -

  TMP_FILE=$(mktemp)

  capture_io "$TMP_FILE" main | $SNACK ghci

  diff golden $TMP_FILE
  rm $TMP_FILE
}

# TODO: Fix cannot coerce a list to a string, at /...-snack-lib/files.nix:66:12
SNACK="snack -j4 -s ./package-src.nix" test

# TODO: Fix cannot coerce a list to a string, at /...-snack-lib/hpack.nix:60:37
SNACK="snack -j4 -p ./package-src.yaml" test

# TODO: Fix cannot coerce a set to a string, at /...-snack-lib/files.nix:66:12
SNACK="snack -j4 -s ./package-pkg.nix" test

# TODO: Fix attribute 'lib2' missing, at /...-snack-lib/default.nix:22:18
SNACK="snack -j4 -p ./package-pkg-name-2.yaml" test

# TODO: Fix attribute 'lib1' missing, at /...-snack-lib/default.nix:22:18
SNACK="snack -j4 -p ./package-pkg-name-12.yaml" test
